# Generated by Django 5.0.6 on 2025-10-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='places_main/', verbose_name='Главное изображение'),
        ),
        migrations.AddField(
            model_name='place',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='places_gallery/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(blank=True, verbose_name='Полное описание'),
        ),
    ]
