# Generated by Django 5.0.6 on 2025-10-26 10:41

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_image_options_image_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='short_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Краткое описание'),
        ),
    ]
