# Generated by Django 5.0.6 on 2025-10-26 10:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_place_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='short_description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Краткое описание'),
        ),
    ]
