# Generated by Django 5.0.6 on 2025-10-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_place_latitude_place_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.FloatField(default=55.75, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.FloatField(default=37.62, verbose_name='Долгота'),
        ),
    ]
